# -*- coding: utf-8 -*-
"""Week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uTONsJjXhdqHtXQLLLQgo6-Y0HwnIzBs
"""

from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/covid-19/'

import cv2
from PIL import Image
from os import listdir
import skimage
from skimage.transform import resize
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import os

from sklearn.model_selection import train_test_split, KFold
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix

def get_data(folder, X=[], y=[]):
 
  for folderName in listdir(folder)[:2]:
    # print(folderName) - used for debugging purposes
    if not folderName.startswith('.') and not folderName.endswith('.ipynb'): # to not consider .DS_Store and .ipynb files
      if folderName in ['normal']:
        label = 0
      elif folderName in ['corona']:
        label = 1
      # elif folderName in ['normal']:
        # label = 2 # for all other types of pnuemonia - label 2 is to be used later on
      # print(label) - used for debugging purposes
      for image_filename in tqdm(listdir(folder + folderName)):
        img_file = cv2.imread(folder + folderName + '/' + image_filename)
        if img_file is not None:
          img_file = skimage.transform.resize(img_file, (224, 224, 3))
          img_arr = np.asarray(img_file)
          X.append(img_arr)
          y.append(label)
  X = np.asarray(X)
  y = np.asarray(y)
  return X,y

X,y = get_data(path)
print(len(X), len(y))